# Copyright 2020 Axel Huebl
#
# This file is part of WarpX.
#
# License: BSD-3-Clause-LBNL

name: bot

on:
  pull_request:
    types: [labeled]

jobs:
  # This bot:
  #   - replaces TABs to four spaces
  #   - removes EOL whitespaces
  fix-spaces:
    if: github.event.label.name == 'bot: spaces'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fix Spaces
      run: |
        eval "$(.github/workflows/source/hasTabs)"
        eval "$(.github/workflows/source/hasEOLwhiteSpace)"
    - name: Commit Changes
      run: |
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git fetch github
        git add .
        git commit -m "Bot: Fix Spaces" --author "Tools <warpx@lbl.gov>"
        git push github HEAD:${GITHUB_REF}
    - name: Unlabel
      run: |
        echo "TODO: Remove Label"
